### ISSUE TITLE
I don't understand the meaning of cron config option

### ISSUE THREAD

**Issue by m-danya** [AkashRajpurohit/git-sync#63] opened 2024-11-05 19:45 UTC
### Describe the Bug

Nothing happens at the supposed cron execution time

### Steps to reproduce

Here is my `~/.config/git-sync/config.yaml`:

```
username: m-danya
token: <MY_TOKEN_IS_HERE>
include_forks: false
clone_type: bare
cron: 45 22 * * *
platform: github
backup_dir: .git-sync-repos
server:
  domain: github.com
  protocol: https
```

I ran `git-sync`, got this:

```
{"level":"info","time":"2024-11-05T22:38:36.677+0300","message":"Logger initialized"}
{"level":"info","time":"2024-11-05T22:38:36.678+0300","message":"Config loaded from: /home/m-danya/.config/git-sync/config.yaml"}
{"level":"info","time":"2024-11-05T22:38:36.678+0300","message":"Validating config ⏳"}
{"level":"info","time":"2024-11-05T22:38:36.678+0300","message":"Valid config found ✅"}
{"level":"info","time":"2024-11-05T22:38:36.678+0300","message":"Using Platform: github"}
{"level":"info","time":"2024-11-05T22:38:36.678+0300","message":"Cron job scheduled to run at: 45 22 * * *"}
```
It doesn't exited (here I begin to doubt that I understood the meaning of the parameter correctly), so I kill it with Ctrl+C. I thought at this point the git-sync should have set up systemd timer or cron, IDK. I just follow the docs.

Nothing happend at 22:45. My `.git-sync-repos` is empty.

But when I run `git-sync` manually (and before that I delete the `cron` param from the config), it runs smoothly.

I thought the `cron` config option was made as an option to set up cron or systemd timer. But apparently it just runs in a forever loop and wait the specified time? Am I supposed to create systemd service to run this utililty at the system startup? If its true, it should be mentioned in the documentation, it's kind of frustrating..

### Which version of the software are you using?

0.11.1

### Which operating system are you using?

Linux Mint 21 (based on Ubuntu 22)

### runtime

Binary

**Comment by m-danya** [comment] 2024-11-05 20:16
I've used the docker compose and it works fine. I think the docs on the `--cron` option should be updated. I thought it will set up a cron job for me, as it says this in the docs:

> There are mainly two ways to set up periodic backups for git-sync:
> 1. Use the --cron flag or the cron option in the config file to set up git-sync in cron mode.
> 2. Use the default flags and set up cronjobs yourself on your system.

So either it's a bug or the docs should be updated. Thanks.

**Comment by m-danya** [comment] 2024-11-05 20:44
Also, the `--restart unless-stopped` is missing for the `docker run` command in the docs

**Comment by AkashRajpurohit** [comment] 2024-11-06 05:38
Thanks for bringing this up, I'll update the docs to better reflect what the purpose of the cron option is.

Essentially if you run it in cron mode, you need to either run it via docker or setup systemd service so it runs in the background, if you kill the service the it will stop the process.

You can manually set up a cronjob as well (which is what it was proposed earlier) but later I added an in-built cron option so it can work out of the box for multiple OS.

Once I update the doc, I'll close this issue, but this is not a bug.

**Comment by AkashRajpurohit** [comment] 2024-12-20 07:05
@m-danya I have updated the Wiki with bit more information and a sample Systemd service file for users who want to use the `--cron` option with git-sync. let me know if there is still some confusion around it.

**Closed** 2024-12-20 14:29 UTC
Labels: documentation, planned
